spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:mysql://127.0.0.1:3306/blog
    # url: jdbc:mysql://127.0.0.1:3306/blog
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.backlog: debug
  file:
    path: log/blog-dev.log
